stokyeni/Controllers/SalataController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRulers_fluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace tekrar_100ders.Controllers
{
    public class SalataController : Controller
    {

        SalataManager sam = new SalataManager(new EFSalataDal());

       

   
        public ActionResult Index()
        {
            var Salatavalues = sam.GetList();
            return View(Salatavalues);
        }

        [HttpGet]
        public ActionResult AddSalata()
        {
         
            return View();
        }

        [HttpPost]
        public ActionResult AddSalata(Salata p)
        {
            //cm.EFSalataService(p);
            SalataValidator SalataValidator = new SalataValidator();
            ValidationResult results = SalataValidator.Validate(p);


            if (results.IsValid)
            {
                sam.SalataAdd(p);
                return RedirectToAction("index");
            }
            else

            {
                foreach (var item in results.Errors)
                {

                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }


            return View(); /*RedirectToAction("GetSalataList");*/

        }
        public ActionResult DeleteSalata(int id) //ayrı bir sayfa yapmayacagız indexte sil yapacagız.
        {
            var Salatavalue = sam.GetByID(id);
            sam.SalataDelete(Salatavalue);
            return RedirectToAction("index"); //indexe gönderdik
        }

        [HttpGet]
        public ActionResult EditSalata(int id)

        {
    

            var Salatavalue = sam.GetByID(id);
            return View(Salatavalue);
        }

        [HttpPost]
        public ActionResult EditSalata(Salata p)
        {
            sam.SalataUpdate(p);
            return RedirectToAction("index");
        }
    }
}

stokyeni/Views/Salata/AddSalata.cshtml
@model EntityLayer.Concrete.Salata
@{
    ViewBag.Title = "AddSalata";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<center><h2>Tatlı Ekleme Sayfası</h2></center>
@using (Html.BeginForm("AddSalata", "Salata", FormMethod.Post))
{
    <br />
    <center><h2>Tatlı ekle</h2></center>
    <div class="form-group">
        <label>Tatlı Adı</label>

        @Html.TextBoxFor(x => x.SalataName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.SalataName)
        <br /><br />

        <label>Fiyat</label>

        @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Fiyat)


        <br /><br />


        <br /><br />
        <button id="kaydetButton">Kaydet</button>

        <script>
            var kaydetButton = document.getElementById("kaydetButton");
            kaydetButton.style.backgroundColor = "#000000";
            kaydetButton.style.color = "white";
            kaydetButton.style.border = "none";
            kaydetButton.style.padding = "10px 20px";
            kaydetButton.style.borderRadius = "5px";
        </script>
    </div>
    }

stokyeni/Views/Salata/EditSalata.cshtml
@model EntityLayer.Concrete.Salata
@{
    ViewBag.Title = "EditSalata";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<center><h2>Kategori Düzenleme Sayfası</h2></center>
@using (Html.BeginForm("EditSalata", "Salata", FormMethod.Post))
{
    <div class="form-group" style="margin-left:20px">

        @Html.Label("Salata ID")
        @Html.TextBoxFor(x => x.SalataID, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.SalataID)
        <br /> <br />
        @Html.Label("Tatlı Adı")
        @Html.TextBoxFor(x => x.SalataName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.SalataName)
        <br /><br />
        @Html.Label("Fiyat")
        @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Fiyat)
        <br /><br />

        <button id="kaydetButton">Kaydet</button>

        <script>
            var kaydetButton = document.getElementById("kaydetButton");
            kaydetButton.style.backgroundColor = "#000000";
            kaydetButton.style.color = "white";
            kaydetButton.style.border = "none";
            kaydetButton.style.padding = "10px 20px";
            kaydetButton.style.borderRadius = "5px";
        </script>
    </div>



}

stokyeni/Views/Salata/Index.cshtml
@using EntityLayer.Concrete
@model List<Salata>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<center><h2> Salata Listesi</h2></center>
<div><br />
    <form method="post" action="/Salata/index">
        <table class="table table-hover">
            <tr>
              
                <th>SalataID</th>
                <th>Salata Adı</th>
                <th>Fiyat</th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>

                    <td>@item.SalataID</td>
                    <td>@item.SalataName</td>
                    <td>@item.Fiyat</td>

                    <td><a href="/Salata/DeleteSalata/@item.SalataID" class="btn btn-danger"> sil</a></td>
                    <td><a href="/Salata/EditSalata/@item.SalataID" class="btn btn-success"> güncelle</a></td>

                </tr>
            }
        </table>

    </form>
</div>
<a href="/Salata/AddSalata" class="btn btn-info">Ekle</a>

@*<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <h2 class="modal-title">satış</h2>

            </div>
            <form>

                <div class="modal-body"></div>.
            </form>
        </div>
    </div>
</div>

<br /><br /><br /><br /><br /><br /><br />*@