stokyeni/Controllers/SatisController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRulers_fluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace tekrar_100ders.Controllers
{
    public class SatisController : Controller
    {

        SatisManager sm = new SatisManager(new EFSatisDal());

        TatliManager tm = new TatliManager(new EFTatliDal());


        YemekManager ym = new YemekManager(new EFYemekDal());

        MenuManager mm = new MenuManager(new EFMenuDal());

        SalataManager sam = new SalataManager(new EFSalataDal());



   
        public ActionResult Index()
        {
            var Satisvalues = sm.GetList();
            return View(Satisvalues);
        }


        [HttpGet]
        public ActionResult AddSatis()
        {



            List<SelectListItem> valueTatli = (from x in tm.GetList()
                                               select new SelectListItem
                                               {
                                                   Text = x.TatliName + "  (" + x.Fiyat + "₺)",
                                                   Value = x.TatliID.ToString()

                                               }
                                                   ).ToList();
            ViewBag.vlt = valueTatli;


            List<SelectListItem> valueYemek = (from x in ym.GetList()
                                               select new SelectListItem
                                               {
                                                   Text = x.YemekName + "  (" + x.Fiyat + "₺)",
                                                   Value = x.YemekID.ToString()

                                               }
                                                ).ToList();
            ViewBag.vly = valueYemek;

            List<SelectListItem> valueMenu = (from x in mm.GetList()
                                               select new SelectListItem
                                               {
                                                   Text = x.MenuName + "  (" + x.Fiyat + "₺)",
                                                   Value = x.MenuID.ToString()

                                               }
                                                ).ToList();
            ViewBag.vlm = valueMenu;

            List<SelectListItem> valueSalata = (from x in sam.GetList()
                                               select new SelectListItem
                                               {
                                                   Text = x.SalataName + "  (" + x.Fiyat + "₺)",
                                                   Value = x.SalataID.ToString()

                                               }
                                                ).ToList();
            ViewBag.vlsa = valueSalata;

       



            return View();
        }

       

        [HttpPost]
        public ActionResult AddSatis(Satis p)
        {
            //tm.EFIcecekService(p);
            SatisValidator SatisValidator = new SatisValidator();

            ValidationResult results = SatisValidator.Validate(p);


            if (results.IsValid)
            {
                p.Tarih = DateTime.Now;

                sm.SatisAdd(p);
                return RedirectToAction("index");
            }
            else

            {
                foreach (var item in results.Errors)
                {

                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }


            return View();

        }


        //[HttpPost]
        //public ActionResult AddSatis(List<SiparisDetay> siparisDetaylari)
        //{
        //    try
        //    {
        //        // siparisDetaylari'yi veritabanına kaydedin
        //        // Burada veritabanına kaydetme mantığınızı ekleyin

        //        return Json(new { success = true, message = "Sipariş başarıyla kaydedildi!" });
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new { success = false, message = "Sipariş kaydedilirken hata oluştu: " + ex.Message });
        //    }
        //}


        public ActionResult DeleteSatis(int id) //ayrı bir sayfa yapmayacagız indexte sil yapacagız.
        {
            var Satisvalue = sm.GetByID(id);
            sm.SatisDelete(Satisvalue);
            return RedirectToAction("index"); //indexe gönderdik
        }


        //// Get Metodu, Bu metod ne işe yarar: Geriye Yemek listesini döndürecek
        //[HttpGet]
        //public List<String> YemekList()
        //{
        //    List<String> yemekler = new List<String>();  

        //    List<Yemek> yemekListesi =  ym.GetList().ToList();

        //    foreach (var yemek in yemekListesi)
        //    {
        //        //Debug.WriteLine($"Yemek ID: {yemek.YemekID}, Yemek Adı: {yemek.YemekName}, Fiyat: {yemek.Fiyat}");
        //        yemekler.Add(yemek.YemekName);
        //    }

        //    return yemekler;
        //}



        [HttpGet]
        public ActionResult DetailSatis(int id)
        {


            List<SelectListItem> GetvalueTatli = (from x in tm.GetList()
                                               select new SelectListItem
                                               {
                                                   Text = x.TatliName + "  " + x.Fiyat ,
                                                   Value = x.TatliID.ToString()

                                               }
                                                   ).ToList();
            ViewBag.vlt = GetvalueTatli;


            List<SelectListItem> GetvalueYemek = (from x in ym.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.YemekName + "  " + x.Fiyat,
                                                      Value = x.YemekID.ToString()

                                               }
                                                ).ToList();
            ViewBag.vly = GetvalueYemek;

            List<SelectListItem> valueMenu = (from x in mm.GetList()
                                              select new SelectListItem
                                              {
                                                  Text = x.MenuName + "  " + x.Fiyat,
                                                  Value = x.MenuID.ToString()

                                              }
                                                ).ToList();
            ViewBag.vlm = valueMenu;

            List<SelectListItem> GetEditSatis = (from x in sam.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.SalataName + "  " + x.Fiyat,
                                                    Value = x.SalataID.ToString()

                                                }
                                                ).ToList();
            ViewBag.vlsa = GetEditSatis; 

            var Satisvalue = sm.GetByID(id);
            return View(Satisvalue);
        }

        [HttpPost]
        public ActionResult DetailSatis(Satis p)
        {


            p.Tarih = DateTime.Now;


            sm.SatisUpdate(p);
            return RedirectToAction("index");
        }


        [HttpGet]
        public ActionResult EditSatis(int id)
        {


            List<SelectListItem> GetvalueTatli = (from x in tm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.TatliName + "  " + x.Fiyat,
                                                      Value = x.TatliID.ToString()

                                                  }
                                                   ).ToList();
            ViewBag.vlt = GetvalueTatli;


            List<SelectListItem> GetvalueYemek = (from x in ym.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.YemekName + "  " + x.Fiyat,
                                                      Value = x.YemekID.ToString()

                                                  }
                                                ).ToList();
            ViewBag.vly = GetvalueYemek;

            List<SelectListItem> valueMenu = (from x in mm.GetList()
                                              select new SelectListItem
                                              {
                                                  Text = x.MenuName + "  " + x.Fiyat,
                                                  Value = x.MenuID.ToString()

                                              }
                                                ).ToList();
            ViewBag.vlm = valueMenu;

            List<SelectListItem> GetEditSatis = (from x in sam.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.SalataName + "  " + x.Fiyat,
                                                     Value = x.SalataID.ToString()

                                                 }
                                                ).ToList();
            ViewBag.vlsa = GetEditSatis;

            var Satisvalue = sm.GetByID(id);

stokyeni/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>AdminLTE 3 | Dashboard 3</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="~/IndexCont/index" class="nav-link">
                <CENTER> <span class="brand-text font-weight-light">STOK KONTROL</span></CENTER>
            </a>
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->

                        <li class="nav-item">
                            <a href="~/AdminKategori/index" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                   Kategori

                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="~/Urun/index" class="nav-link">
                                <i class="nav-icon fas fa-dolly"></i>
                                <p>
                                    Ürünler
                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="~/Musteri/index" class="nav-link">
                                <i class="nav-icon fas fa-user-friends" ></i>
                                <p>
                                    Müşteri
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="~/Satis/index" class="nav-link">
                                <i class="nav-icon fas fa-shopping-basket"></i>
                                <p>
                                    Satış

                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                @RenderBody()

                <!-- /.container-fluid -->
                <footer><center>  <p>&copy; @DateTime.Now.Year - Sinan Cesur</p></center></footer>
            </div>
            <!-- /.content -->
        </div>

        <!-- /.content-wrapper -->
    </div>

    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.js"></script>
    <!-- OPTIONAL SCRIPTS -->
    <script src="~/AdminLTE-3.0.4/plugins/chart.js/Chart.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/pages/dashboard3.js"></script>
</body>
</html>

stokyeni/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Stok Kontrol", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @*//deneme*@
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Ürünler", "GetUrunList", "Urun", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Kategoriler", "GetCategoryList", "Category", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Satışlar", "GetSatisList", "Satis", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Müşteriler",  "GetMusteriList", "Musteri", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
        <footer>
            <p>&copy; @DateTime.Now.Year - Sinan Cesur</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>