stokyeni/Controllers/YemekController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRulers_fluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace tekrar_100ders.Controllers
{
    public class YemekController : Controller
    {

        YemekManager ym = new YemekManager(new EFYemekDal());

       

   
        public ActionResult Index()
        {
            var Yemekvalues = ym.GetList();
            return View(Yemekvalues);
        }

        [HttpGet]
        public ActionResult AddYemek()
        {
         
            return View();
        }

        [HttpPost]
        public ActionResult AddYemek(Yemek p)
        {
            //cm.EFYemekService(p);
            YemekValidator YemekValidator = new YemekValidator();
            ValidationResult results = YemekValidator.Validate(p);


            if (results.IsValid)
            {
                ym.YemekAdd(p);
                return RedirectToAction("index");
            }
            else

            {
                foreach (var item in results.Errors)
                {

                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }


            return View(); /*RedirectToAction("GetYemekList");*/

        }
        public ActionResult DeleteYemek(int id) //ayrı bir sayfa yapmayacagız indexte sil yapacagız.
        {
            var Yemekvalue = ym.GetByID(id);
            ym.YemekDelete(Yemekvalue);
            return RedirectToAction("index"); //indexe gönderdik
        }

        [HttpGet]
        public ActionResult EditYemek(int id)

        {
    

            var Yemekvalue = ym.GetByID(id);
            return View(Yemekvalue);
        }

        [HttpPost]
        public ActionResult EditYemek(Yemek p)
        {
            ym.YemekUpdate(p);
            return RedirectToAction("index");
        }
    }
}

stokyeni/Views/Yemek/AddYemek.cshtml
@model EntityLayer.Concrete.Yemek
@{
    ViewBag.Title = "AddYemek";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<center><h2>Yemek Ekleme Sayfası</h2></center>
@using (Html.BeginForm("AddYemek", "Yemek", FormMethod.Post))
{
    <br />
    <center><h2>Yemek ekle</h2></center>
    <div class="form-group">
        <label>Yemek Adı</label>

        @Html.TextBoxFor(x => x.YemekName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.YemekName)
        <br /><br />
        <label>Fiyat</label>
        @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Fiyat)

        <br /><br />



        <br /><br />


        <br /><br />
        <button id="kaydetButton">Kaydet</button>

        <script>
            var kaydetButton = document.getElementById("kaydetButton");
            kaydetButton.style.backgroundColor = "#000000";
            kaydetButton.style.color = "white";
            kaydetButton.style.border = "none";
            kaydetButton.style.padding = "10px 20px";
            kaydetButton.style.borderRadius = "5px";
        </script>
    </div>
    }

stokyeni/Views/Yemek/EditYemek.cshtml
@model EntityLayer.Concrete.Yemek
@{
    ViewBag.Title = "EditYemek";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<center><h2> Yemek DÜzenleme</h2></center>
@using (Html.BeginForm("EditYemek", "Yemek", FormMethod.Post))
{
    <div class="form-group" style="margin-left:20px">

        @Html.Label("Yemek ID")
        @Html.TextBoxFor(x => x.YemekID, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.YemekID)
        <br /> <br />
        @Html.Label("Yemek Adı")
        @Html.TextBoxFor(x => x.YemekName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.YemekName)
        <br /><br />
        @Html.Label("Fiyat")
        @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Fiyat)
        <br /><br />
        <button id="kaydetButton">Kaydet</button>

        <script>
            var kaydetButton = document.getElementById("kaydetButton");
            kaydetButton.style.backgroundColor = "#000000";
            kaydetButton.style.color = "white";
            kaydetButton.style.border = "none";
            kaydetButton.style.padding = "10px 20px";
            kaydetButton.style.borderRadius = "5px";
        </script>
    </div>



}

stokyeni/Views/Yemek/Index.cshtml
@using EntityLayer.Concrete
@model List<Yemek>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<center><h2> Yemek Listesi</h2></center>
<div><br />
    <form method="post" action="/Yemek/index">
        <table class="table table-hover">
            <tr>
              
                <th>YemekID</th>
                <th>Yemek Adı</th>
                <th>Fiyat</th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    
                    <td>@item.YemekID</td>
                    <td>@item.YemekName</td>
                    <td>@item.Fiyat</td>
                    <td><a href="/Yemek/DeleteYemek/@item.YemekID" class="btn btn-danger"> sil</a></td>
                    <td><a href="/Yemek/EditYemek/@item.YemekID" class="btn btn-success"> güncelle</a></td>

                </tr>
            }
        </table>

    </form>
</div>
<a href="/Yemek/AddYemek" class="btn btn-info">Ekle</a>

@*<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <h2 class="modal-title">satış</h2>

            </div>
            <form>

                <div class="modal-body"></div>.
            </form>
        </div>
    </div>
</div>

<br /><br /><br /><br /><br /><br /><br />*@